### PR TITLE
Warning about folder name docker

### PR DESCRIPTION
**Pull request by edevosc2c**
Too many people are failing into this issue. Give a warning before https://github.com/georchestra/docker/issues/214 is solved.

### CODE REVIEW

**Review by jeanmi151 — APPROVED** [review]

**Comment by jeanpommier** [comment]
We can also specify a project name when running docker compose, that should be enough (in our case, `-p docker`). Which still allows people to change the folder's name.

**Comment by superbully** [comment]
If you change the folder´s name, for example docker2 and running docker compose with -p docker2 not work for me.
In the traefik dashboard i can view the error: "the service "static-docker@docker" does not exist " .
someone could help me ?
Thank you so much.

**Comment by jeanpommier** [comment]
> If you change the folder´s name, for example docker2 and running docker compose with -p docker2 not work for me. In the traefik dashboard i can view the error: "the service "static-docker@docker" does not exist " . someone could help me ? Thank you so much.

Of course. `@docker` refers to the project's name and is hardcoded in the traefik configuration. This is why if you change the folder name, for instance docker2, you'd have to use `-p docker` to have it match `@docker`.
Alternatively, in docker-compose.override.yml, you can replace every occurrence of `@docker` by your folder's name, it should work too.

**Comment by superbully** [comment]
> > If you change the folder´s name, for example docker2 and running docker compose with -p docker2 not work for me. In the traefik dashboard i can view the error: "the service "static-docker@docker" does not exist " . someone could help me ? Thank you so much.
> 
> Of course. `@docker` refers to the project's name and is hardcoded in the traefik configuration. This is why if you change the folder name, for instance docker2, you'd have to use `-p docker` to have it match `@docker`. Alternatively, in docker-compose.override.yml, you can replace every occurrence of `@docker` by your folder's name, it should work too.

Hello, sorry for the inconvenience .
I have tried but it does not work ...
I do as follows:
1.- I rename the folder docker by docker2 .
2.- I replace in the file "docker-compose.override.yml" docker by docker2 .
3.- I run the project with "docker-compose -p docker2 up -d" .

Thank you very much in advance.

**Comment by edevosc2c** [comment]
@superbully I guess you could try with this solution: https://github.com/georchestra/docker/issues/214#issuecomment-2262046412
Revert all the changes that you did about "docker2" in the various files. Keep the folder named "docker2"

**Comment by superbully** [comment]
> @superbully I guess you could try with this solution: [#214 (comment)](https://github.com/georchestra/docker/issues/214#issuecomment-2262046412) Revert all the changes that you did about "docker2" in the various files. Keep the folder named "docker2"
@edevosc2c Hello I try with this solution: https://github.com/georchestra/docker/issues/214#issuecomment-2262046412 and it doesn't work or I'm not doing it right . 
I have done the following:
1.- I rename the folder docker by docker2 .
2.- I have changed in the file "docker-compose.override.yml" only the line "- "traefik.http.routers.traefik.middlewares=traefik-strip@docker2"
3.- I run the project with "docker-compose -p docker2 up -d" .

it doesn't work that way either

**Comment by edevosc2c** [comment]
1. Don't change anything in the files yet, do the usual quick start: https://github.com/georchestra/docker?tab=readme-ov-file#quick-start
2. Change the folder name like from docker to docker2
3. Launch the docker composition with the `docker` compose name: `docker-compose -p docker up -d`

Don't try to change from `docker` to `docker2` in traefik files, there are too many lines to change.

**Comment by superbully** [comment]
> 1. Don't change anything in the files yet, do the usual quick start: https://github.com/georchestra/docker?tab=readme-ov-file#quick-start
> 2. Change the folder name like from docker to docker2
> 3. Launch the docker composition with the `docker` compose name: `docker-compose -p docker up -d`
> 
> Don't try to change from `docker` to `docker2` in traefik files, there are too many lines to change.

Hello, this way it works . But I need several environments on the same machine (development, testing, ...), so the name of the containers need to be different, otherwise, collisions occur. With the solution you propose, although the folder is different, it is no longer docker, the project name is still docker, so the containers are still called docker_******* . If I raise another project on the same server, errors occur because containers with the same name are already running.
Thank you very much for the help.

**Comment by edevosc2c** [comment]
Understandable. I would like to remind that this docker composition is for development only, there are no guarantees for production usage.

Once you cross the line of "something that doesn't exist out of the box", you are on your own. This is an open source project ran by volunteers, not a product with a dedicated support team.

There is a pending PR that will solve the issue related to docker compose names by not depending on it anymore, but it's not yet merged: https://github.com/georchestra/docker/pull/268. Feel free to test it and give your feedback there.

**Comment by superbully** [comment]
> Understandable. I would like to remind that this docker composition is for development only, there are no guarantees for production usage.
> 
> Once you cross the line of "something that doesn't exist out of the box", you are on your own. This is an open source project ran by volunteers, not a product with a dedicated support team.
> 
> There is a pending PR that will solve the issue related to docker compose names by not depending on it anymore, but it's not yet merged: #268. Feel free to test it and give your feedback there.



> Understandable. I would like to remind that this docker composition is for development only, there are no guarantees for production usage.
> 
> Once you cross the line of "something that doesn't exist out of the box", you are on your own. This is an open source project ran by volunteers, not a product with a dedicated support team.
> 
> There is a pending PR that will solve the issue related to docker compose names by not depending on it anymore, but it's not yet merged: #268. Feel free to test it and give your feedback there.

Hello, good morning.
Thank you very much for your reply. I am sorry if I have insisted too much with the folder name and docker problem. I am well aware that the project is an open source project that is maintained by people in a disinterested way. 
I am part of a working group of the UCLM university in which we are using Georchestra for a project. We will continue testing and if we find a solution we will share it.
Thank you very much for the help and for trying to help me. 


Translated with DeepL.com (free version)

**Comment by jeanpommier** [comment]
> I am part of a working group of the UCLM university in which we are using Georchestra for a project. We will continue testing and if we find a solution we will share it.

Alternatively, you might want to look at our [helm chart](https://github.com/georchestra/helm-georchestra). 

- If you are on Windows, Docker desktop can be configured to support kubernetes and I tested it successfully using the helm chart, not long ago.
- if you are on linux, there are several solutions for a light kubernetes environment. On light production environments, I like k3s, which is reasonably simple to steup.

**Comment by superbully** [comment]
> > I am part of a working group of the UCLM university in which we are using Georchestra for a project. We will continue testing and if we find a solution we will share it.
> 
> Alternatively, you might want to look at our [helm chart](https://github.com/georchestra/helm-georchestra).
> 
> * If you are on Windows, Docker desktop can be configured to support kubernetes and I tested it successfully using the helm chart, not long ago.
> * if you are on linux, there are several solutions for a light kubernetes environment. On light production environments, I like k3s, which is reasonably simple to steup.

hello, thank you very much for the information. the solution you propose is the one we are studying. our development environment is linux. we will continue testing and investigating.
thank you very much for sharing your knowledge and trying to solve the problems we are having @jeanpommier @edevosc2c  
I am very grateful.
Regards.

**Comment by edevosc2c** [comment]
Fixed by https://github.com/georchestra/docker/pull/268

**Comment by superbully** [comment]
Thank you so much !!
Regards.

**Pull request closed without merging**
