### PR TITLE
Added port so that the service-name of static is independent

### LINKED ISSUE #214: Directory name needs to be named "docker"
The directory name needs to be named `docker` and not something else. Or we will have issues for the security proxy routing.

Probably related to `@docker`: https://github.com/georchestra/docker/blob/master/docker-compose.override.yml#L43

Possible solutions:
- Find a way to make this work whatever the directory name
- Big warning in the README for the directory name.

### PR DESCRIPTION
**Pull request by hpwjnijs**
So traefik sees the 'static' service as static-\<directory\>@docker and that how it is addressed. But you want to have it directory independant. There is no direct way to name/label your service , but according to [this](https://stackoverflow.com/questions/66158478/how-to-set-traefik-2-4-service-name-in-docker-compose-labels) you can fix this by e.g. 
```
labels:
  - traefik.http.services.<<name_of_service>>.loadbalancer.server.port=80
```
So, that's what we do here.
It fixes https://github.com/georchestra/docker/issues/214

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Many thanks for the contribution !

**Comment by hpwjnijs** [comment]
Second change (about the .env) was meant to be in a different pull request.  It should address https://github.com/georchestra/docker/issues/219

**Comment by hpwjnijs** [comment]
Bonjour François,

You're welcome. I do use gitlab but never github. So I messed up trying to
make 2 different Pull Requests.
I´m inclined to delete the messed-up-version, and try again.
What do you think?

Merci d'avance, Huub

**Comment by fvanderbiest** [comment]
Yes sure, go ahead. Thanks !

**Comment by edevosc2c** [comment]
hello @hpwjnijs did you have time to split the PR :)? thank you

**Comment by hpwjnijs** [comment]
I will close this PR, and make 2 new ones for the unrelated issues.

**Comment by hpwjnijs** [comment]
Hi Emilien,

Yes, I (just) did.  Thanks for asking: I use gitlab a lot not github, but I
somehow managed.

Cheers, Huub

Op di 14 mei 2024 om 10:58 schreef Emilien Devos ***@***.***>:

**Pull request closed without merging**
