### PR TITLE
Remove doc that is not needed anymore

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Follow https://github.com/georchestra/docker/pull/151/files

### CODE REVIEW

**Comment by Gaetanbrl** [comment]
Well, @arnaud-morvan force traefik port is useless with this PR ?

**Comment by Gaetanbrl** [comment]
@arnaud-morvan can't really test :

After checkout master (or this PR branch), all modules url return `//////` like : 

https://georchestra-127-0-1-1.traefik.me/console/////////////////////

**Comment by arnaud-morvan** [comment]
@Gaetanbrl : I already added it permanently in https://github.com/georchestra/docker/pull/151/files during code print

I suspect that those redirection (//////) are related with changes from @fvanderbiest concerning ending slash redirections : https://github.com/georchestra/docker/commit/1e37bbb4a295445d37f79d7808c94f12c30bbac7 (see "Add trailing slash to well-known apps")

**Comment by Gaetanbrl** [comment]
> are related with changes from @fvanderbiest concerning ending slash

yes @arnaud-morvan , i'd see that after my comment.

Is it expected or wrong behavior ?

**Comment by arnaud-morvan** [comment]
I proposed a fix for ending slash redirections : https://github.com/georchestra/docker/pull/164

**Comment by Gaetanbrl** [comment]
I'm now testing it.

**Comment by Gaetanbrl** [comment]
Seems better but not works with console @arnaud-morvan .

https://georchestra-127-0-1-1.traefik.me/ - OK
https://georchestra-127-0-1-1.traefik.me/mapstore/#/home - OK
https://georchestra-127-0-1-1.traefik.me/logout - 404 not found

Each `console/` or `console` or `console/manager/` redirect to : 

https://georchestra-127-0-1-1.traefik.me/console/manager///////////////////

... but 

https://georchestra-127-0-1-1.traefik.me/console/account/userdetails -> OK

... and click onto "users" redirect to 

https://georchestra-127-0-1-1.traefik.me/console/manager///////////////////

**Comment by Gaetanbrl** [comment]
@arnaud-morvan i dont arrive to connect Eclipse to port 5005.

Could you confirm if my config is right please ?

### Error 

```
Failed to connect to remote VM
com.sun.jdi.connect.spi.ClosedConnectionException
```


### Docker containers 

OK ==> sec proxy ==> 0.0.0.0:5005=>5005/tcp 

image

### docker-compose.override.yml 

```
  proxy:
    image: georchestra/security-proxy:22.0.x
    depends_on:
      - ldap
      - database
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
      - XMS=256M
      - XMX=1G
    restart: always
    ports:
      - "5005:5005"
```

### Eclipse config (remote java application)

I thing this is wrong / or wrong type / or wrong host :

image

**Comment by arnaud-morvan** [comment]
Sorry but I do not have any java support in Eclipse, so I cannot reproduce, but everything seems OK.

Here is my Idea config and I can connect the debugger: 

Screenshot from 2023-02-14 16-53-20

Is Eclipse installed in Windows while docker run on you Linux VM ?

Can I merge this PR as traefik config has already been merged in master ?

**Comment by Gaetanbrl** [comment]
> Can I merge this PR as traefik config has already been merged in master ?

I guess.

> Is Eclipse installed in Windows while docker run on you Linux VM ?

All in same Debian env.
Project env seems not installed as Java view (same issue for VS code). Need to install maven dep and others...

> Here is my Idea config and I can connect the debugger:

Think your capture is enough for everybody need more details about IDE debug config.

**Review by Gaetanbrl — APPROVED** [review]

**Comment by Gaetanbrl** [comment]
Just to try, i had installed IDEA @arnaud-morvan and connexion seems denied

> Error running 'sec-proxy-docker': Unable to open debugger port (localhost:5005): java.net.ConnectException "Connexion refusée"


After re update each image => Each works with IDEA.

Nice !

Thanks.

**Comment by Gaetanbrl** [comment]
> Here is my Idea config 

If other people search info, i just complete with VS Code config example to debug (remote java) : 

```
"version": "0.2.0",
"configurations": [
    {
        "type": "java",
        "name": "Debug (Attach)",
        "projectName": "sec-proxy-debug",
        "request": "attach",
        "hostName": "localhost",
        "port": 5005
    }
]
```

Only change `hostName`  and `port` if needed.

However, a doc section about debug could be a better place instead of random PRs comment.

**Pull request merged**
