### PR TITLE
Remove georchestra analytics

### PR DESCRIPTION
**Pull request by edevosc2c**
Remove georchestra analytics since we can't use it because security proxy was removed.

Also remove security proxy file in envsubst.

This commit may be good to backport in georchestra/docker 24.0

### CODE REVIEW

**Comment by fvanderbiest** [comment]
> This commit may be good to backport in georchestra/docker 24.0

Nope. 
geOrchestra 24 is meant to be usable with both the security-proxy and the gateway.

But I see your point. 
The docker composition has the gateway by default on branch 24.

Maybe commenting out analytics would be a better option in this branch.
In the same idea, having the security-proxy commented out would also make sense in the same branch.

**Comment by edevosc2c** [comment]
> Maybe commenting out analytics would be a better option in this branch.

Fine for me too.

> In the same idea, having the security-proxy commented out would also make sense in the same branch.

Well security-proxy is gone from the docker composition: https://github.com/georchestra/docker/blob/24.0/docker-compose.yml and https://github.com/georchestra/docker/pull/197/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L82-L88

So I thought analytics wouldn't be necessary anymore too.

Maybe we need to bring back SP but commented? And comment analytics.

**Comment by jeanpommier** [comment]
What about the header. Won't we have a broken entry (analytics) ?

**Comment by edevosc2c** [comment]
Closing in favor of https://github.com/georchestra/docker/pull/305

**Pull request closed without merging**
