### PR TITLE
Replace security proxy by gateway  into georchestra docker

### PR DESCRIPTION
**Pull request by jeanmi151**
@emmdurin I rebased with the new docker version files

work coming from here : https://github.com/georchestra/docker/pull/168

### CODE REVIEW

**Comment by fvanderbiest** [comment]
targeting 23.1, do not merge before 23.0 release

**Comment by jeanmi151** [comment]
yes, also it is still not working properly, for example now we can't reach /import (to add datasets)

**Comment by jahow** [comment]
also the datahub apparently cannot be reached on that branch

**Comment by jeanmi151** [comment]
> also the datahub apparently cannot be reached on that branch

yes import as well

**Comment by jahow** [comment]
import and datahub services will be accessible once this is merged: https://github.com/georchestra/datadir/pull/299

**Comment by jeanmi151** [comment]
this is a PR and custom branch, no need to stick to what is merged (you can use whatever sub branch you want)

**Comment by edevosc2c** [comment]
Note: we will need to add a check dependency on rabbitmq.

**Comment by jeanmi151** [comment]
i added rabbitmq here and remove it from master in here : https://github.com/georchestra/docker/pull/262

**Comment by edevosc2c** [comment]
just rebased against master

**Comment by f-necas** [comment]
Closes https://github.com/georchestra/georchestra/issues/3881

**Comment by f-necas** [comment]
Mentionned in : https://github.com/georchestra/helm-georchestra/pull/91

**Review by f-necas — APPROVED** [review]
LGTM we just need https://github.com/georchestra/datadir/pull/403 to be merged.

**Pull request merged**
