### PR TITLE
comment ldap var

### PR DESCRIPTION
**Pull request by jeanmi151**
There is a mix of var for the LDAP container
because from other container it is  good
but from the container ldap it should be localhost

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Sounds really weird to me.

Asking for a review from @pmauduit and/or @edevosc2c 
Thanks !

**Comment by edevosc2c** [comment]
Isn't that the case for likely a lot of other environments variables?

I mean why not the comment but in this case it should be written on a lot of other environments variables.

**Comment by jeanmi151** [comment]
I also added the env var for ldap password policy bootstrap, SLAPD_PASSWORD_MGT_POLICY
Yes it could be a problem for others container but we didn't remark any problem on other, only for ldap was creating a real problem (don't start at all)

**Comment by fvanderbiest** [comment]
> I mean why not the comment but in this case it should be written on a lot of other environments variables.

My concern was about having a variable which "should not be changed" - it does not make sense to me...
Where is this var used, is it really useful ?

**Comment by jeanmi151** [comment]
if removed, we need to delete if from the envs-ldap file, but it could be moved into hosted, I will test it !

**Comment by jeanmi151** [comment]
hum can't make working cas ... not sure it is coming from my config,

**Comment by jeanmi151** [comment]
I am getting the error from cas : 
```
Caused by: 
org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'cas-org.apereo.cas.configuration.CasConfigurationProperties': Could not bind properties to 'CasConfigurationProperties' : prefix=cas, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'cas.host' to org.apereo.cas.configuration.model.core.HostProperties

Caused by: 
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'cas.host' to org.apereo.cas.configuration.model.core.HostProperties

Caused by: 
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.boot.context.properties.NestedConfigurationProperty org.apereo.cas.configuration.model.core.HostProperties]
```

**Review by edevosc2c — APPROVED** [review]

**Comment by jeanmi151** [comment]
still couldn't make cas working, don't know why

**Comment by fvanderbiest** [comment]
The PR misses a description of which problem it tackles, how it solves it, and why it is needed.
Considering closing it.

**Comment by jeanmi151** [comment]
I guess we can close this PR, did not see again the problem

**Pull request closed without merging**
