### PR TITLE
Adding a volume for mapstore's uploaded extensions

### LINKED ISSUE #116: mapstore - dynamic datadir is missing
in https://github.com/georchestra/docker/blob/f978d8c322856b1e635086bc8076652d6f525857/docker-compose.yml#L173-L180

### PR DESCRIPTION
**Pull request by fvanderbiest**
fixes #116

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Did this a long time ago. 
Not sure this is relevant anymore - @tkohr ?

**Comment by fvanderbiest** [comment]
Also @pmauduit : I think we've got a clearer picture of the situation nowadays

**Comment by pmauduit** [comment]
I don't know for the clearer picture but this is what we do for geo2france currently (and in the helm chart for georchestra):
- a classic georchestra datadir into /etc/georchestra
- a "dynamic whatever" datadir into /mnt/mapstore2

See https://github.com/camptocamp/helm-georchestra/#mapstore2--georchestra-datadir

**Review by pmauduit — APPROVED** [review]

**Comment by catmorales** [comment]
> I don't know for the clearer picture but this is what we do for geo2france currently (and in the helm chart for georchestra)

As for us ;=) and the dynamic datadir must be writable. cf  http://docs.georchestra.geo-solutions.it/en/latest/configuration/application/index.html#advanced-map-viewer-configuration

**Pull request merged**
